# Generated by Django 2.1 on 2020-05-13 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('code', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=2083)),
                ('discount', models.FloatField(verbose_name=0.2)),
            ],
        ),
    ]
